server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    gzip on;
    gzip_types text/css application/javascript text/plain;

    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-cache";
    }

    location ~* \.(css|js)$ {
        expires 1h;
        add_header Cache-Control "public, max-age=3600, must-revalidate";
    }
}
